services:
  x5_ner_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: x5-ner-service:latest
    container_name: x5_ner_service
    ports:
      - "8000:8000"
    env_file: .env
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --log-config=logconf.ini -n x5_ner_service
    restart: unless-stopped
    volumes:
      - ./app:/opt/app
      - ./model:/opt/model
      - ./gunicorn.conf.py:/opt/gunicorn.conf.py
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]